--<ScriptOptions statementTerminator=";"/>

CREATE TABLE JAVA_KEYSTORE (
		ID VARCHAR2(255) NOT NULL,
		KEYSTORE CLOB,
		KS_TYPE VARCHAR2(255)
	);

CREATE UNIQUE INDEX SYS_JKS ON JAVA_KEYSTORE (ID ASC);

ALTER TABLE JAVA_KEYSTORE ADD CONSTRAINT SYS_JKS PRIMARY KEY (ID);

