--<ScriptOptions statementTerminator=";"/>

CREATE TABLE LOGGER (
		ID VARCHAR2(255) NOT NULL,
		LOG4J CLOB
	);

CREATE UNIQUE INDEX SYS_LOGGER ON LOGGER (ID ASC);

ALTER TABLE LOGGER ADD CONSTRAINT SYS_LOGGER PRIMARY KEY (ID);

