<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://provider.poc.saml.itst.dk/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsaws="http://www.w3.org/2005/08/addressing" xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
	xmlns:t="http://schemas.xmlsoap.org/ws/2005/02/trust" xmlns:sc="http://schemas.sun.com/2006/03/wss/server"
	xmlns:wspp="http://java.sun.com/xml/ns/wsit/policy" targetNamespace="http://provider.poc.saml.itst.dk/" name="ProviderService">
	<wsp:UsingPolicy />
		<wsp:Policy wsu:Id="PortBindingPolicy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding>
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken>
								
								</sp:HttpsToken>
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic128 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:IncludeTimestamp/>
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:Wss11>
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
						<sp:MustSupportRefThumbprint />
						<sp:MustSupportRefEncryptedKey />
					</wsp:Policy>
				</sp:Wss11>
				<sp:SignedSupportingTokens sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/Always">
					<wsp:Policy>
						<sp:SamlToken>
							<wsp:Policy>
								<sp:WssSamlV20Token11 />
							</wsp:Policy>
						</sp:SamlToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	
	<types>
		<xs:schema>
			<xs:import namespace="http://provider.poc.saml.itst.dk/"
				schemaLocation="ProviderService_schema1.xsd">
			</xs:import>
		</xs:schema>
	</types>
	<message name="echo">
		<part name="parameters" element="tns:echo"></part>
	</message>
	<message name="echoResponse">
		<part name="parameters" element="tns:echoResponse"></part>
	</message>
	<portType name="Provider">
		<operation name="echo">
			<input message="tns:echo"></input>
			<output message="tns:echoResponse"></output>
		</operation>
	</portType>
	<binding name="ProviderPortBinding" type="tns:Provider">
		<wsp:PolicyReference URI="#PortBindingPolicy" />
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"></soap:binding>
		<operation name="echo">
			<soap:operation soapAction=""></soap:operation>
			<input>
				<soap:body use="literal"></soap:body>
			</input>
			<output>
				<soap:body use="literal"></soap:body>
			</output>
		</operation>
	</binding>
	<service name="ProviderService">
		<port name="ProviderPort" binding="tns:ProviderPortBinding">
			<soap:address location="http://localhost:8080/poc-provider/ProviderService"></soap:address>
		</port>
	</service>
</definitions>